"""
Django settings for backtoyou project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Configuracion sensible: se lee del entorno para no dejarla en el codigo.
# En desarrollo se usan los valores por defecto y no hay que configurar nada.
# En despliegue hay que definir DJANGO_SECRET_KEY, DJANGO_DEBUG=False y
# DJANGO_ALLOWED_HOSTS con los dominios reales.

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-solo-para-desarrollo-local-no-usar-en-despliegue",
)

DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() != "false"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'accounts',
    'reports',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backtoyou.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backtoyou.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# La base de datos y los archivos subidos son LOCALES de cada persona.
# Usan nombres que nunca estuvieron rastreados en git ('local.sqlite3' y
# 'media_local/'), asi que ninguna operacion de git -merge, pull, checkout-
# puede borrarlos: git solo toca archivos que conoce.

DB_NAME = os.environ.get("DJANGO_DB_NAME", "local.sqlite3")
MEDIA_DIR = os.environ.get("DJANGO_MEDIA_DIR", "media_local")


def _vacio(ruta):
    # Un archivo de 0 bytes o un directorio sin contenido no son datos.
    if not ruta.exists():
        return True
    if ruta.is_dir():
        return not any(ruta.iterdir())
    return ruta.stat().st_size == 0


def _renombrar_si_quedo_el_nombre_viejo(viejo, nuevo):
    # Mueve los datos al nombre nuevo la primera vez, sin perderlos.
    # Solo actua si el origen tiene contenido y el destino no: es
    # idempotente y nunca sobreescribe datos.
    origen, destino = BASE_DIR / viejo, BASE_DIR / nuevo
    if _vacio(origen) or not _vacio(destino):
        return
    if destino.exists():
        destino.rmdir() if destino.is_dir() else destino.unlink()
    origen.rename(destino)


_renombrar_si_quedo_el_nombre_viejo("db.sqlite3", DB_NAME)
_renombrar_si_quedo_el_nombre_viejo("media", MEDIA_DIR)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / DB_NAME,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# El ajuste se llama EMAIL_BACKEND. Con el nombre equivocado Django caia a
# su valor por defecto (SMTP contra localhost:25) y las notificaciones
# fallaban en silencio, tapadas por el try/except de email_notifications.py.
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = "BackToYou noreply@backtoyou.local"
AUTH_USER_MODEL = "accounts.User"
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"
MEDIA_URL ="/media/"
MEDIA_ROOT = BASE_DIR / MEDIA_DIR
